### ISSUE TITLE
Error when request is in a different directory than mediator: Cannot find element with key: Request

### ISSUE THREAD

**Issue by alexandrereyes** [m4ss1m0g/mediatr-ts#18]
I have a very simple example to reproduce the issue:

/src/handlers.ts
```
import { requestHandler, IRequestHandler } from 'mediatr-ts'
import { Request } from './requests';

@requestHandler(Request)
class HandlerTest implements IRequestHandler<Request, string> {
    handle(value: Request): Promise<string> {
        return Promise.resolve(`Value passed ${value.name}`);
    }
}
```

/src/requests.ts
```
import { IRequest } from "mediatr-ts";

export class Request implements IRequest<string> {
    name!: string;
}
```

/src/index.ts
```
import { Mediator } from 'mediatr-ts'
import { Request } from './requests';

const mediator = new Mediator();
const request = new Request();
request.name = 'Hello World';

mediator.send(request).then(result => {
    console.log(result)
});
```

when I run the index.ts the exception throws:
`
Exception has occurred: Error: Cannot find element with key: Request
  at Resolver.resolve (C:\dev\typescript-test\node_modules\mediatr-ts\lib\cjs\models\resolver.js:31:19)
    at Mediator.<anonymous> (C:\dev\typescript-test\node_modules\mediatr-ts\lib\cjs\models\mediator.js:67:72)
    at step (C:\dev\typescript-test\node_modules\mediatr-ts\lib\cjs\models\mediator.js:33:23)
    at Object.next (C:\dev\typescript-test\node_modules\mediatr-ts\lib\cjs\models\mediator.js:14:53)
    at C:\dev\typescript-test\node_modules\mediatr-ts\lib\cjs\models\mediator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\dev\typescript-test\node_modules\mediatr-ts\lib\cjs\models\mediator.js:4:12)
    at Mediator.send (C:\dev\typescript-test\node_modules\mediatr-ts\lib\cjs\models\mediator.js:60:16)
    at Object.<anonymous> (C:\dev\typescript-test\dist\index.js:8:10)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
`

any help?

**Comment by alexandrereyes** [comment]
you should import the handler to the index.ts, it'll be nice to mention this in the docs.

`import './handlers'`
